version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: core-database
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: HUNGDEPZAI
      MYSQL_DATABASE: ZentDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: HUNGDEPZAI
    volumes:
      - mysql-data:/var/lib/mysql

  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    restart: unless-stopped
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # Alloy UI
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "/etc/alloy/config.alloy"
    ]
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_USER=${GRAFANA_CLOUD_USER}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}

volumes:
  mysql-data:
    name: zent_mysql_data
