//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "add_new_part_form")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub part_number: String,
    pub mtm: String,
    pub part_types_id: i32,
    pub serial_number: String,
    pub description: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::add_part_request_images::Entity")]
    AddPartRequestImages,
    #[sea_orm(
        belongs_to = "super::part_types::Entity",
        from = "Column::PartNumber",
        to = "super::part_types::Column::PartNumber",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartTypes,
    #[sea_orm(
        belongs_to = "super::product_models::Entity",
        from = "Column::Mtm",
        to = "super::product_models::Column::ModelCode",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ProductModels,
}

impl Related<super::add_part_request_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AddPartRequestImages.def()
    }
}

impl Related<super::part_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartTypes.def()
    }
}

impl Related<super::product_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
