//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_room_image_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: Uuid,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::images::Entity",
        from = "Column::ImageId",
        to = "super::images::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Images,
    #[sea_orm(
        belongs_to = "super::chat_rooms::Entity",
        from = "Column::RoomId",
        to = "super::chat_rooms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChatRooms,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::chat_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRooms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
