//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub room_name: String,
    pub created_by: Uuid,
    pub work_order_id: Option<Uuid>,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
    #[sea_orm(has_many = "super::chat_room_members::Entity")]
    ChatRoomMembers,
    #[sea_orm(has_many = "super::chat_room_image_links::Entity")]
    ChatRoomImageLinks,
    #[sea_orm(
        belongs_to = "super::work_orders::Entity",
        from = "Column::WorkOrderId",
        to = "super::work_orders::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    WorkOrders,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::chat_room_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomMembers.def()
    }
}

impl Related<super::chat_room_image_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatRoomImageLinks.def()
    }
}

impl Related<super::work_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
