//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checklist_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::work_order_closing_form_checklist_results::Entity")]
    WorkOrderClosingFormChecklistResults,
}

impl Related<super::work_order_closing_form_checklist_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderClosingFormChecklistResults.def()
    }
}

impl Related<super::work_order_closing_forms::Entity> for Entity {
    fn to() -> RelationDef {
        super::work_order_closing_form_checklist_results::Relation::WorkOrderClosingForms
            .def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::work_order_closing_form_checklist_results::Relation::ChecklistItems
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
