//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "equipments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub equipment_status_id: i32,
    pub model_id: i32,
    pub customer_id: Uuid,
    pub equipment_name: String,
    pub serial_number: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::equipment_models::Entity",
        from = "Column::ModelId",
        to = "super::equipment_models::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    EquipmentModels,
    #[sea_orm(
        belongs_to = "super::equipment_status::Entity",
        from = "Column::EquipmentStatusId",
        to = "super::equipment_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    EquipmentStatus,
    #[sea_orm(has_many = "super::image::Entity")]
    Image,
    #[sea_orm(has_many = "super::parts::Entity")]
    Parts,
    #[sea_orm(has_many = "super::warranty::Entity")]
    Warranty,
}

impl Related<super::equipment_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EquipmentModels.def()
    }
}

impl Related<super::equipment_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EquipmentStatus.def()
    }
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Image.def()
    }
}

impl Related<super::parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parts.def()
    }
}

impl Related<super::warranty::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Warranty.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
