//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "equipment_models")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub model_name: String,
    pub model_code: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::equipments::Entity")]
    Equipments,
}

impl Related<super::equipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Equipments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
