//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "image")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub image_url: String,
    pub part_id: Option<Uuid>,
    pub equipment_id: Option<Uuid>,
    pub captured_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::equipments::Entity",
        from = "Column::EquipmentId",
        to = "super::equipments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Equipments,
    #[sea_orm(
        belongs_to = "super::parts::Entity",
        from = "Column::PartId",
        to = "super::parts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Parts,
}

impl Related<super::equipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Equipments.def()
    }
}

impl Related<super::parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
