//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "part_types")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub part_number: String,
    pub commodity_type: String,
    pub description: String,
    pub part_status_id: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::images::Entity")]
    Images,
    #[sea_orm(has_many = "super::parts_by_model::Entity")]
    PartsByModel,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::parts_by_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartsByModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
