//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "part_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub part_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub work_order_closing_form_id: Uuid,
    pub change_type: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::parts::Entity",
        from = "Column::PartId",
        to = "super::parts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Parts,
    #[sea_orm(
        belongs_to = "super::work_order_closing_forms::Entity",
        from = "Column::WorkOrderClosingFormId",
        to = "super::work_order_closing_forms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WorkOrderClosingForms,
}

impl Related<super::parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parts.def()
    }
}

impl Related<super::work_order_closing_forms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderClosingForms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
