//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub product_id: Option<Uuid>,
    pub part_status_id: i32,
    pub customer_id: Uuid,
    pub part_name: String,
    pub quantity: i32,
    pub serial_number: Option<String>,
    pub last_modified_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Products,
    #[sea_orm(has_many = "super::images::Entity")]
    Images,
    #[sea_orm(
        belongs_to = "super::part_status::Entity",
        from = "Column::PartStatusId",
        to = "super::part_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PartStatus,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::part_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
