//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_model_image_links")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_model_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::images::Entity",
        from = "Column::ImageId",
        to = "super::images::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Images,
    #[sea_orm(
        belongs_to = "super::product_models::Entity",
        from = "Column::ProductModelCode",
        to = "super::product_models::Column::ModelCode",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ProductModels,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::product_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
