//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub model_id: i32,
    pub customer_id: Uuid,
    pub serial_number: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::images::Entity")]
    Images,
    #[sea_orm(has_many = "super::parts_by_model::Entity")]
    PartsByModel,
    #[sea_orm(
        belongs_to = "super::product_models::Entity",
        from = "Column::ModelId",
        to = "super::product_models::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ProductModels,
    #[sea_orm(has_many = "super::warranties::Entity")]
    Warranties,
    #[sea_orm(has_many = "super::work_orders::Entity")]
    WorkOrders,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::parts_by_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartsByModel.def()
    }
}

impl Related<super::product_models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModels.def()
    }
}

impl Related<super::warranties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Warranties.def()
    }
}

impl Related<super::work_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
