//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub full_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub phone_number: String,
    pub account_status: i32,
    pub role_id: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_status::Entity",
        from = "Column::AccountStatus",
        to = "super::account_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    AccountStatus,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::RoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Role,
    #[sea_orm(has_many = "super::session::Entity")]
    Session,
}

impl Related<super::account_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountStatus.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
