//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "warranty")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub customer_id: Uuid,
    pub equipment_id: Uuid,
    pub start_date: DateTimeUtc,
    pub end_date: Option<DateTimeUtc>,
    pub warranty_status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::equipments::Entity",
        from = "Column::EquipmentId",
        to = "super::equipments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Equipments,
}

impl Related<super::equipments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Equipments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
