//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "work_orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub first_name: String,
    pub last_name: String,
    pub email: String,
    pub phone_number: String,
    pub work_order_status_id: i32,
    pub country: String,
    pub state: String,
    pub city: String,
    pub address: String,
    pub building: String,
    pub appointment: DateTimeUtc,
    pub reference_ticket: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
    pub admin_id: Uuid,
    pub customer_id: Uuid,
    pub technician_id: Uuid,
    pub complete_form_id: Uuid,
    pub reject_reason: String,
    pub work_order_symptom_id: i32,
    pub product_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::TechnicianId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users3,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CustomerId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AdminId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users1,
    #[sea_orm(
        belongs_to = "super::work_order_closing_forms::Entity",
        from = "Column::RejectReason",
        to = "super::work_order_closing_forms::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    WorkOrderClosingForms2,
    #[sea_orm(
        belongs_to = "super::work_order_closing_forms::Entity",
        from = "Column::CompleteFormId",
        to = "super::work_order_closing_forms::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    WorkOrderClosingForms1,
    #[sea_orm(
        belongs_to = "super::work_order_status::Entity",
        from = "Column::WorkOrderStatusId",
        to = "super::work_order_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    WorkOrderStatus,
    #[sea_orm(
        belongs_to = "super::work_order_symptoms::Entity",
        from = "Column::WorkOrderSymptomId",
        to = "super::work_order_symptoms::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    WorkOrderSymptoms,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::work_order_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderStatus.def()
    }
}

impl Related<super::work_order_symptoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderSymptoms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
