//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "work_order_reject_forms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub approver_id: Uuid,
    pub approved: bool,
    pub reason: Option<String>,
    pub explanation: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ApproverId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Users,
    #[sea_orm(has_many = "super::work_orders::Entity")]
    WorkOrders,
    #[sea_orm(has_many = "super::work_order_reject_form_image_links::Entity")]
    WorkOrderRejectFormImageLinks,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::work_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrders.def()
    }
}

impl Related<super::work_order_reject_form_image_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderRejectFormImageLinks.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        super::work_order_reject_form_image_links::Relation::Images.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::work_order_reject_form_image_links::Relation::WorkOrderRejectForms
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
