//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "work_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub address_string: String,
    pub status_id: i32,
    pub description: String,
    pub reject_reason: String,
    pub priority: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub closed_at: Option<DateTimeUtc>,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::work_order_status::Entity",
        from = "Column::StatusId",
        to = "super::work_order_status::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    WorkOrderStatus,
}

impl Related<super::work_order_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrderStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
