use utoipa::ToSchema;
use serde::{Deserialize, Serialize};
use validator::Validate;

/// Request payload to confirm a media upload after it has been stored in OCI.
#[derive(Debug, Serialize, Deserialize, ToSchema, Validate)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmUploadRequest {
    /// The unique filename generated by the server.
    #[validate(length(min = 1))]
    pub unique_file_name: String,
    /// Geolocation latitude at the time of upload.
    pub latitude: f64,
    /// Geolocation longitude at the time of upload.
    pub longitude: f64,
    /// The phase of the service (e.g., 'pre-disassembly', 'reassembly').
    pub phase: String,
    /// Client-side Unix timestamp when the upload was initiated.
    /// Validated against server time using the `internet_time_drift_minutes` policy.
    pub internet_time: i64,
}
